-- MySQL Script generated by MySQL Workbench
-- Fri May  6 09:35:15 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema autocafedb
-- -----------------------------------------------------
-- The SAAT Dealer Buiz Management Database cafedb

-- -----------------------------------------------------
-- Schema autocafedb
--
-- The SAAT Dealer Buiz Management Database cafedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autocafedb` DEFAULT CHARACTER SET utf8 ;
USE `autocafedb` ;

-- -----------------------------------------------------
-- Table `autocafedb`.`image_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autocafedb`.`image_type` (
  `id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autocafedb`.`catalog_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autocafedb`.`catalog_images` (
  `id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `cdn_url_loc` VARCHAR(150) NOT NULL,
  `image_type_id` BIGINT(8) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_catalog_images_image_type1_idx` (`image_type_id` ASC),
  CONSTRAINT `fk_catalog_images_image_type1`
    FOREIGN KEY (`image_type_id`)
    REFERENCES `autocafedb`.`image_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autocafedb`.`vehicle_image_catalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autocafedb`.`vehicle_image_catalog` (
  `id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `catalog_images_id` BIGINT(8) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicle_image_catalog_catalog_images1_idx` (`catalog_images_id` ASC),
  CONSTRAINT `fk_vehicle_image_catalog_catalog_images1`
    FOREIGN KEY (`catalog_images_id`)
    REFERENCES `autocafedb`.`catalog_images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autocafedb`.`vehicle_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autocafedb`.`vehicle_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autocafedb`.`manufacture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autocafedb`.`manufacture` (
  `ID` INT NOT NULL,
  `full_name` VARCHAR(150) NOT NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CODE_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `FULL_NAME_UNIQUE` (`full_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autocafedb`.`vehicle_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autocafedb`.`vehicle_model` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `make` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  FULLTEXT INDEX `idxMake` (`make` ASC),
  FULLTEXT INDEX `idxModel` (`model` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autocafedb`.`vehicle_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autocafedb`.`vehicle_year` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autocafedb`.`vehicle_inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autocafedb`.`vehicle_inventory` (
  `id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `uid` CHAR(36) NOT NULL,
  `vehicle_price` DECIMAL(10,0) NOT NULL DEFAULT 0.00,
  `vehicle_mileage` VARCHAR(45) NOT NULL DEFAULT '0',
  `created_by` VARCHAR(45) NOT NULL,
  `created_dtm` TIMESTAMP(20) NOT NULL,
  `modified_by` VARCHAR(45) NULL,
  `modefied_dtm` TIMESTAMP(20) NULL,
  `vehicle_image_catalog_id` BIGINT(8) NOT NULL,
  `vehicle_category_id` INT NOT NULL,
  `manufacture_ID` INT NOT NULL,
  `vehicle_model_id` INT NOT NULL,
  `vehicle_year_id` INT NOT NULL,
  PRIMARY KEY (`id`, `vehicle_image_catalog_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uid` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC),
  INDEX `fk_vehicle_inventory_vehicle_image_catalog1_idx` (`vehicle_image_catalog_id` ASC),
  FULLTEXT INDEX `idx_price` (`vehicle_price` ASC),
  INDEX `fk_vehicle_inventory_vehicle_category1_idx` (`vehicle_category_id` ASC),
  INDEX `fk_vehicle_inventory_manufacture1_idx` (`manufacture_ID` ASC),
  INDEX `fk_vehicle_inventory_vehicle_model1_idx` (`vehicle_model_id` ASC),
  INDEX `fk_vehicle_inventory_vehicle_year1_idx` (`vehicle_year_id` ASC),
  CONSTRAINT `fk_vehicle_inventory_vehicle_image_catalog1`
    FOREIGN KEY (`vehicle_image_catalog_id`)
    REFERENCES `autocafedb`.`vehicle_image_catalog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_inventory_vehicle_category1`
    FOREIGN KEY (`vehicle_category_id`)
    REFERENCES `autocafedb`.`vehicle_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_inventory_manufacture1`
    FOREIGN KEY (`manufacture_ID`)
    REFERENCES `autocafedb`.`manufacture` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_inventory_vehicle_model1`
    FOREIGN KEY (`vehicle_model_id`)
    REFERENCES `autocafedb`.`vehicle_model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_inventory_vehicle_year1`
    FOREIGN KEY (`vehicle_year_id`)
    REFERENCES `autocafedb`.`vehicle_year` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
